logout && doc update
CBIIT/bento-auth pull request #31
Opened 2022-07-13 12:58 UTC by knockknockyoo

1. Updated logout API
- NIH & Login.gov accept logout API

2. ejs views template updated
- display IDP type & user's name
- NIH / Google logout

3. Added test routes for development purpose

4. Added restful API test codes

2022-07-13 21:01 UTC, knockknockyoo reviewed
Login.gov also added to pass login authentication.

2022-07-13 21:01 UTC, knockknockyoo commented on idps/index.js
> +        } else if (isCaseInsensitiveEqual(idp,NIH) || isCaseInsensitiveEqual(idp, LOGIN_GOV)) {
Login.gov and NIH will go through authentication.

2022-07-18 17:48 UTC, n2iw requested changes
- README.md line 51 should be "If set to development, a test ...."
- There are unwanted code in the PR such as nihRouter 
- There is a bug related to detect NIH or Login.gov user, if a user use xxxx@nih.gov to register a login.gov user, when he/she logs in, the IDP detected is "NIH" instead of "login.gov"

2022-07-18 20:54 UTC, knockknockyoo reviewed
1. deleted nih router
2. updated README.md
3. preferred_name is only indicator as a login.gov authenticator

2022-07-18 20:54 UTC, knockknockyoo commented on README.md
> +- NODE_ENV: If set to "development", a test html page will be activated in the route "/"
updated NODE_ENV description

2022-07-18 20:54 UTC, knockknockyoo commented on idps/nih.js
> +        const idp = getIDP(user['preferred_username'] ? user['preferred_username'] : user.email);
preferred_username will be used to determine as a login.gov authenticator

2022-07-18 21:20 UTC, n2iw approved these changes

2022-07-18 21:20 UTC, merged